brew "calc"
brew "coreutils"
brew "gawk"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "jq"
brew "mas"
brew "miller"
brew "pandoc"
brew "rsync"
brew "starship"
brew "teleport"
brew "z"
cask "basictex"
cask "macvim"
cask "qlmarkdown"
cask "quicklook-csv"
cask "quicklook-json"
cask "r"
cask "rocket"
cask "rstudio"
cask "signal"
cask "visual-studio-code"
mas "1Password", id: 443987910
mas "Amphetamine", id: 937984704
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Tweetbot", id: 1384080005
